version: '3.3'

volumes:
     mariadb-vol:
        name: mariadb-vol
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/tgriffit/data/mariadb'

     wp-vol:
         name: web-vol
         driver: local
         driver_opts:
             type: 'none'
             o: 'bind'
             device: '/home/tgriffit/data/wordpress'

networks:
    inception:
        name: inception
        driver: bridge

services:
    mariadb:
        container_name: 'mariadb'
        image: 'mariadb:ft_1.0'
        restart: on-failure
        cpus: 2
        networks:
            - inception
        env_file: .env
        build:
            context: requirements/mariadb/
            args:
                - USER=$USER
                - DB_NAME=$DB_NAME
                - PASS_USER=$PASS_USER
                - PASS_ROOT=$PASS_ROOT
        volumes:
            - mariadb-vol:/var/lib/mysql

    wordpress:
        container_name: 'wordpress'
        image: 'wordpress:ft_2.0'
        restart: on-failure
        cpus: 2
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress/
            args:
                - USER
                - ADMIN_USER
                - PASS_USER
                - PASS_ROOT
                - DB_NAME
                - URL
                - WP_PATH:/var/www/html
        volumes:
            - wp-vol:/var/www/html
        networks:
            - inception
        env_file: .env

    nginx:
            container_name: 'nginx'
            image: 'nginx:ft_3.0'
            restart: on-failure
            cpus: 2
            depends_on:
                - wordpress
            build:
                context: requirements/nginx/
                args:
                    - USER
                    - PASS_USER
                    - PASS_ROOT
                    - DB_NAME
                    - WP_PATH:/var/www/html
            volumes:
                - wp-vol:/var/www/html
            ports:
                - 443:443
            networks:
                - inception
            env_file: .env
   