version: '3.3'

volumes:
     mariadb-vol:
         name: mariadb-vol
     wp-vol:
         name: wordpress-vol
     nginx-vol:
         name: nginx-vol

networks:
    inception:
        name: inception
        driver: bridge

services:
    mariadb:
        container_name: 'mariadb'
        image: 'mariadb:ft_1.0'
        restart: on-failure
        networks:
            - inception
       # command: 'mysql -hdatabase -uroot -prootpassword'
        env_file: .env
        build:
            context: requirements/mariadb/
            args:
                - USER=$USER
                - DB_NAME=$DB_NAME
                - PASS_USER=$PASS_USER
                - PASS_ROOT=$PASS_ROOT
        volumes:
            - mariadb-vol:/home/tgriffit/data/mariadb


    wordpress:
        container_name: 'wordpress'
        image: 'wordpress:ft_2.0'
        restart: on-failure
        build:
            context: requirements/wordpress
            args:
                - USER
                - PASS_USER
                - PASS_ROOT
                - DB_NAME
                - WP_PATH:/var/www/html
        volumes:
            - wp-vol:/var/www/html
        networks:
            - inception
        env_file: .env