version: '3.3'
volumes:
     data:
     mysql:
services:
    db:
        image: 'incep:1.0'#'mariadb:10.3'
        container_name: 'rootclient'
        restart: 'no'
        command: 'mysql -hdatabase -uroot -prootpassword'
        ports:
            - '80:3000'
        volumes:
            - data:/var/lib/mysql
            - ./mariadb:/docker-entrypoint-initdb.d
    mysql:
        image: mysql:5.7.22
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: test
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql